#!/bin/bash
# v9-hyprdots bootstrap (simple, best-effort, deterministic)

set -e

# Colors
R='\033[0;31m'
G='\033[0;32m'
C='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${C}"
cat << "EOF"
██╗   ██╗ █████╗     ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  ██████╗ ████████╗███████╗
██║   ██║██╔══██╗    ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝
██║   ██║╚██████║    ███████║ ╚████╔╝ ██████╔╝██████╔╝██║  ██║██║   ██║   ██║   ███████╗
╚██╗ ██╔╝ ╚═══██║    ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║  ██║██║   ██║   ██║   ╚════██║
 ╚████╔╝  ██████║    ██║  ██║   ██║   ██║     ██║  ██║██████╔╝╚██████╔╝   ██║   ███████║
  ╚═══╝   ╚═════╝    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═════╝  ╚═════╝    ╚═╝   ╚══════╝
                                  
EOF
echo -e "${NC}"
echo -e "${C}== v9-hyprdots bootstrap ==${NC}"

# --------------------------------------------------
# Always run from repo root
# --------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --------------------------------------------------
# Arch check
# --------------------------------------------------
[[ -f /etc/arch-release ]] || {
  echo -e "${R}❌ Arch Linux only${NC}"
  exit 1
}

# --------------------------------------------------
# Network check
# --------------------------------------------------
ping -c 1 archlinux.org >/dev/null || {
  echo -e "${R}❌ No internet${NC}"
  exit 1
}

# --------------------------------------------------
# System update
# --------------------------------------------------
echo -e "${C}== System Update ==${NC}"
sudo pacman -S --noconfirm archlinux-keyring
sudo pacman -Syu --noconfirm

# --------------------------------------------------
# Install repo packages (CONTINUE ON FAILURE)
# --------------------------------------------------
echo -e "${C}== Installing packages ==${NC}"

FAILED_PKGS=()

for file in pkgs/*.txt; do
  echo -e "${C}-- $file${NC}"
  while read -r pkg; do
    [[ -z "$pkg" || "$pkg" == \#* ]] && continue
    echo -n "→ $pkg... "
    if sudo pacman -S --needed --noconfirm "$pkg" >/dev/null 2>&1; then
        echo -e "${G}OK${NC}"
    else
        echo -e "${R}FAIL${NC}"
        FAILED_PKGS+=("$pkg")
    fi
  done < "$file"
done

# --------------------------------------------------
# Enable NetworkManager
# --------------------------------------------------
sudo systemctl enable --now NetworkManager >/dev/null 2>&1 || true

# --------------------------------------------------
# Enable Bluetooth & Avahi
# --------------------------------------------------
sudo systemctl enable --now bluetooth >/dev/null 2>&1 || true
sudo systemctl enable --now avahi-daemon >/dev/null 2>&1 || true

# --------------------------------------------------
# Install FetchX
# --------------------------------------------------
echo -e "${C}== Installing FetchX ==${NC}"
curl -fsSL https://raw.githubusercontent.com/v9mirza/fetchx/main/install.sh | bash

# --------------------------------------------------
# Configs
# --------------------------------------------------
echo -e "${C}== Installing configs ==${NC}"

# Required: Hypr entry point
[[ -f config/hypr/hyprland.conf ]] || {
  echo -e "${R}❌ Missing config/hypr/hyprland.conf${NC}"
  exit 1
}

mkdir -p ~/.config

# Backup existing configs
for d in hypr waybar dunst kitty wofi cava btop; do
  if [[ -d ~/.config/$d ]]; then
      echo "Backing up ~/.config/$d"
      mv ~/.config/$d ~/.config/$d.bak
  fi
done

# Copy configs exactly
rsync -av --delete config/ ~/.config/
cp config/mimeapps.list ~/.config/mimeapps.list

# Make scripts executable
chmod +x ~/.config/hypr/scripts/*.sh 2>/dev/null || true

# --------------------------------------------------
# Safety: block autogenerated Hypr config
# --------------------------------------------------
if grep -q "autogenerated = 1" ~/.config/hypr/hyprland.conf; then
  echo -e "${R}❌ Autogenerated Hypr config detected${NC}"
  exit 1
fi

# --------------------------------------------------
# Ensure Hyprland exists
# --------------------------------------------------
command -v Hyprland >/dev/null || sudo pacman -S --noconfirm hyprland

# --------------------------------------------------
# Wayland session entry
# --------------------------------------------------
sudo mkdir -p /usr/share/wayland-sessions
sudo tee /usr/share/wayland-sessions/hyprland.desktop >/dev/null <<EOF
[Desktop Entry]
Name=Hyprland
Exec=Hyprland
Type=Application
EOF

# --------------------------------------------------
# Shell Setup (Starship)
# --------------------------------------------------
if ! grep -q "starship init bash" ~/.bashrc; then
  echo -e "${C}== Configuring Shell ==${NC}"
  echo 'eval "$(starship init bash)"' >> ~/.bashrc
  echo -e "${G}→ Added Starship to ~/.bashrc${NC}"

fi

# --------------------------------------------------
# GTK Theme Setup (No-Look)
# --------------------------------------------------
echo -e "${C}== Configuring GTK Theme ==${NC}"
mkdir -p ~/.config/gtk-3.0
cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=Sans 11
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-application-prefer-dark-theme=1
EOF
echo -e "${G}→ Applied Papirus-Dark Icons & Dark Theme${NC}"

if ! grep -q "fetchx" ~/.bashrc; then
  cat <<EOF >> ~/.bashrc

# Auto-run fetchx
if [[ \$SHLVL -eq 1 ]] && command -v fetchx >/dev/null; then
  fetchx
fi
EOF
  echo -e "${G}→ Added FetchX to ~/.bashrc startup${NC}"
fi

# --------------------------------------------------
# Summary
# --------------------------------------------------
echo
echo -e "${G}✅ Bootstrap complete${NC}"

if (( ${#FAILED_PKGS[@]} )); then
  echo
  echo -e "${R}⚠ Packages that failed to install:${NC}"
  printf '  - %s\n' "${FAILED_PKGS[@]}"
fi

echo
echo "Login:"
echo "  - Display Manager → select Hyprland"
echo "  - TTY → run: Hyprland"
