#!/bin/bash
# v9-hyprdots bootstrap (simple, best-effort, deterministic)

set -e

echo "== v9-hyprdots bootstrap =="

# --------------------------------------------------
# Always run from repo root
# --------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --------------------------------------------------
# Arch check
# --------------------------------------------------
[[ -f /etc/arch-release ]] || {
  echo "❌ Arch Linux only"
  exit 1
}

# --------------------------------------------------
# Network check
# --------------------------------------------------
ping -c 1 archlinux.org >/dev/null || {
  echo "❌ No internet"
  exit 1
}

# --------------------------------------------------
# System update
# --------------------------------------------------
sudo pacman -S --noconfirm archlinux-keyring
sudo pacman -Syu --noconfirm

# --------------------------------------------------
# Install repo packages (CONTINUE ON FAILURE)
# --------------------------------------------------
echo "== Installing packages =="

FAILED_PKGS=()

for file in pkgs/*.txt; do
  echo "-- $file"
  while read -r pkg; do
    [[ -z "$pkg" || "$pkg" == \#* ]] && continue
    echo "→ $pkg"
    if ! sudo pacman -S --needed --noconfirm "$pkg"; then
      echo "⚠ Skipped: $pkg"
      FAILED_PKGS+=("$pkg")
    fi
  done < "$file"
done

# --------------------------------------------------
# Enable NetworkManager
# --------------------------------------------------
sudo systemctl enable --now NetworkManager >/dev/null 2>&1 || true

# --------------------------------------------------
# Install FetchX
# --------------------------------------------------
echo "Installing FetchX (Default Tool)"
curl -fsSL https://raw.githubusercontent.com/v9mirza/fetchx/main/install.sh | bash

# --------------------------------------------------
# Configs
# --------------------------------------------------
echo "== Installing configs =="

# Required: Hypr entry point
[[ -f config/hypr/hyprland.conf ]] || {
  echo "❌ Missing config/hypr/hyprland.conf"
  exit 1
}

mkdir -p ~/.config

# Backup existing configs
for d in hypr waybar dunst kitty wofi cava btop; do
  [[ -d ~/.config/$d ]] && mv ~/.config/$d ~/.config/$d.bak
done

# Copy configs exactly
rsync -av --delete config/ ~/.config/
cp config/mimeapps.list ~/.config/mimeapps.list

# Make scripts executable
chmod +x ~/.config/hypr/scripts/*.sh 2>/dev/null || true

# --------------------------------------------------
# Safety: block autogenerated Hypr config
# --------------------------------------------------
if grep -q "autogenerated = 1" ~/.config/hypr/hyprland.conf; then
  echo "❌ Autogenerated Hypr config detected"
  exit 1
fi

# --------------------------------------------------
# Ensure Hyprland exists
# --------------------------------------------------
command -v Hyprland >/dev/null || sudo pacman -S --noconfirm hyprland

# --------------------------------------------------
# Wayland session entry
# --------------------------------------------------
sudo mkdir -p /usr/share/wayland-sessions
sudo tee /usr/share/wayland-sessions/hyprland.desktop >/dev/null <<EOF
[Desktop Entry]
Name=Hyprland
Exec=Hyprland
Type=Application
EOF

# --------------------------------------------------
# Shell Setup (Starship)
# --------------------------------------------------
if ! grep -q "starship init bash" ~/.bashrc; then
  echo "== Configuring Shell =="
  echo 'eval "$(starship init bash)"' >> ~/.bashrc
  echo "→ Added Starship to ~/.bashrc"

fi

if ! grep -q "fetchx" ~/.bashrc; then
  cat <<EOF >> ~/.bashrc

# Auto-run fetchx
if [[ \$SHLVL -eq 1 ]] && command -v fetchx >/dev/null; then
  fetchx
fi
EOF
  echo "→ Added FetchX to ~/.bashrc startup"
fi

# --------------------------------------------------
# Summary
# --------------------------------------------------
echo
echo "✅ Bootstrap complete"

if (( ${#FAILED_PKGS[@]} )); then
  echo
  echo "⚠ Packages that failed to install:"
  printf '  - %s\n' "${FAILED_PKGS[@]}"
fi

echo
echo "Login:"
echo "  - Display Manager → select Hyprland"
echo "  - TTY → run: Hyprland"
